### ISSUE TITLE
회원가입 - ID 중복 확인 기능

### ISSUE THREAD

**Issue by elephant97** [f-lab-edu/melody-market#3]
* [x] API 설계
* [x] API 구현
   * [x] ID 중복 확인 기능
   * [x] 닉네임 중복 확인 기능
   * [x] 유저 등록 기능
      * [x] 패스워드 암호화

**Comment by elephant97** [comment]
### google sheet API 명세 작성

https://docs.google.com/spreadsheets/d/1WWOPT-jHhY7EV9786Kyj224zGdnAZzWxkWbKt1N-bw4/edit#gid=0

**Comment by f-lab-kube** [comment]
회원가입을 하나의 PR로 만들면 커질것 같으니 적당한 규모로 따로 브랜치 따서 작업해야하는게 좋을것 같습니다

**Comment by elephant97** [comment]
> 회원가입을 하나의 PR로 만들면 커질것 같으니 적당한 규모로 따로 브랜치 따서 작업해야하는게 좋을것 같습니다 github에서 subtask 기능이 제공되는지 모르겠네요

넵 유저 아이디 중복 체크 기능, 닉네임 중복 체크 기능, 회원 가입 기능 3부분으로 분리해서 이슈 생성하여 진행하겠습니다
